fix: using bignumber in vault amount
Delphor-finance/webapp pull request #27
Opened 2022-02-20 20:06 UTC by RodrigoCSolari

2022-02-20 23:05 UTC, arcollector requested changes

2022-02-20 23:05 UTC, arcollector commented on src/shared/wallet/contract/helpers.ts
> +export const truncateStringAmount = (amount: string, decimals: number) => {
podrias poner como comentario de esta funcion que hace con unn ejemplo, te paso este string y decimales y otengo esto

2022-02-20 23:05 UTC, arcollector commented on src/shared/wallet/contract/helpers.ts
> +export const LamportsToString = (bn: BN) => {
podras poner como comentario de esta funncionnn que hahce con unn ejemplo

2022-02-20 23:05 UTC, arcollector commented on src/shared/wallet/contract/helpers.ts
> +export const removeRightZero = (decimalPart: string) => {
aca tambienn

2022-02-21 20:31 UTC, RodrigoCSolari commented on src/shared/wallet/contract/helpers.ts
> +export const truncateStringAmount = (amount: string, decimals: number) => {
perfecto

2022-02-21 20:31 UTC, RodrigoCSolari commented on src/shared/wallet/contract/helpers.ts
> +export const LamportsToString = (bn: BN) => {
perfecto

2022-02-21 20:31 UTC, RodrigoCSolari commented on src/shared/wallet/contract/helpers.ts
> +export const removeRightZero = (decimalPart: string) => {
perfecto

2022-02-21 20:34 UTC, RodrigoCSolari commented
agregue el nuevo contrato, ya que se deployo una nueva version

2022-02-22 18:08 UTC, arcollector requested changes

2022-02-22 18:08 UTC, arcollector commented on src/shared/wallet/hooks/useBalance.ts
> +      `${account.account.data.parsed.info.tokenAmount.amount}`,
que esto?, porque no directamente `new BN(account.account.data.parsed.info.tokenAmount.amount)` ??

2022-02-22 18:08 UTC, arcollector commented on src/shared/wallet/contract/helpers.ts
> +//truncateStringAmount: recibe un string de un numero que puede o no ser con decimales (9 decimales) y lo retorna truncado, salvo que al truncar solo queden ceros en el decimal y en ese caso trunca h
te pasastes de la columna 100, metele salto de lineas por favor,
hace este mismo cambio en los otros comments

2022-02-24 19:58 UTC, RodrigoCSolari commented on src/shared/wallet/hooks/useBalance.ts
> +      `${account.account.data.parsed.info.tokenAmount.amount}`,
si, modificado

2022-02-24 19:58 UTC, RodrigoCSolari commented on src/shared/wallet/contract/helpers.ts
> +//truncateStringAmount: recibe un string de un numero que puede o no ser con decimales (9 decimales) y lo retorna truncado, salvo que al truncar solo queden ceros en el decimal y en ese caso trunca h
entendido!

2022-02-26 02:12 UTC, arcollector approved these changes

2022-02-27 19:25 UTC, merged