Liquidity provider changes
Delphor-finance/webapp pull request #29
Opened 2022-03-06 07:10 UTC by RodrigoCSolari

2022-03-07 20:42 UTC, arcollector requested changes

2022-03-07 20:42 UTC, arcollector commented on src/Pools/components/ConfigPopUp/SliderPreserveConfig.tsx
> +  console.log(parseFloat(props.amount));
:rage:

2022-03-07 20:42 UTC, arcollector commented on .eslintrc
> +    "@typescript-eslint/ban-ts-comment":"off",
que es esto?

2022-03-07 21:25 UTC, RodrigoCSolari commented on src/Pools/components/ConfigPopUp/SliderPreserveConfig.tsx
> +  console.log(parseFloat(props.amount));
se me paso, ese componente se tuvo que cambiar por un input, me falto borrarlo

2022-03-07 21:29 UTC, RodrigoCSolari commented on .eslintrc
> +    "@typescript-eslint/ban-ts-comment":"off",
una funcion de solana spl-tokens no se reconoce la importacion, pero si importa la funcion.
Es en shared/wallet/contract/helpers, en wrapSol linea 330 aprox, al final hay un ts-ignore. lo hice con lucio en una de las reuiones, si sabes como solucionarlo podriamos sacarlo

2022-03-09 00:42 UTC, arcollector requested changes

2022-03-09 00:42 UTC, arcollector commented on src/shared/wallet/contract/helpers.ts
> +import { coinsSymbol, mintsAddress } from '..';
esto es muy mal!!!!!! nunca se importa asi, esto es bochazo a marzo, importa exactamente lo que queres poniendo el path exacto

2022-03-10 22:45 UTC, arcollector approved these changes

2022-03-11 19:04 UTC, merged